### PR TITLE
CI config, and lints

### PR DESCRIPTION
**Pull request by clbarnes**
This CI config is largely complete. It passes on everything but MacOS, due to the clang issue noted in the readme. I'm not sure the best way to approach that here, but I'm pretty sure the macOS environments have brew, which is a good start. You can run conditional steps but you can't export environment variables in one step to be used in another. I guess we could have something like 

```yaml
# ci.yaml:jobs.test.steps
- if: startsWith(matrix.runs-on, "macos")
  run: |
    brew install llvm
    # ... set environment variables
    pip install -e .
- if "!(startsWith(matrix.runs-on, 'macos'))"
  run: pip install -e .
```

and the same in the deploy steps. The quoting around the negative conditional is, I believe, necessary to prevent the YAML parser throwing a fit around the bang.

Notes:

- The benchmarks run on every OS, but only 1 python version to save time
- I'm not sure whether the deploy config works, but either way will need a `pypi_token` environment variable in the repo settings

### CODE REVIEW

**Comment by schlegelp** [comment]
Cool! Re building on OSX: scikit-learn is using Cython and builds with GitHub. It's a fairly complicated setup but there might be some helpful stuff in this file: https://github.com/scikit-learn/scikit-learn/blob/main/build_tools/github/build_wheels.sh

**Comment by schlegelp** [comment]
Btw: shall I move this repo to navis-org so you have more control?

**Comment by clbarnes** [comment]
I don't think I have much more to contribute so whatever's best for what you want for it!

**Comment by schlegelp** [comment]
Thanks @clbarnes! Shall I merge this PR then?

**Comment by clbarnes** [comment]
Yes, I think so! There may be some extra work needed for the macos and deploy builds but you're probably in a better position for finishing those.

**Pull request merged**
